services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass your_password_here --appendonly yes
    restart: unless-stopped

volumes:
  redis-data:
    driver: local